version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_crochet
    restart: unless-stopped
    env_file:
      - .env 
    ports:    
      - "${PORT}:${PORT}"
