version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db_crochet
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_crochet
    restart: unless-stopped
    env_file:
      - .env 
    ports:    
      - "${PORT}:${PORT}"
    command: sh -c "npm run seed && npm start"

volumes:
  db_data