name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run format check (optional)
        run: npm run format -- --check
        continue-on-error: true

      - name: Run lint check
        run: npm run lint

      - name: Run tests
        env:
          PORT: ${{ secrets.PORT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_PUBLIC_URL: ${{ secrets.DATABASE_PUBLIC_URL }}
          NODE_ENV: "test"
        run: npm test

      - name: Build project
        run: npm run build
